
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: {{ .Values.registry.namespace }} 
  labels:
    component: registry-ui
spec:
  type: NodePort
  selector:
    app: registry-ui
  ports:
  - port: 8080
    targetPort: 80
    nodePort: {{ .Values.ui.nodeport }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: {{ .Values.registry.namespace }}
  labels:
    app: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
      - name: registry-ui
        image: konradkleine/docker-registry-frontend:v2
        env:
        - name: ENV_DOCKER_REGISTRY_HOST
          value: registry
        - name: ENV_DOCKER_REGISTRY_PORT
          value: "5000"
        ports:
        - containerPort: 80

